export const endPoints = {
  account: 'account',
  accounts: 'accounts',
  companies: 'companies',
  contacts: 'contacts',
  content: 'content',
  errors: 'errors',
  login: 'auth/login',
  invitationFinish: 'auth/invitation-finish',
  loginGoogle: 'auth/login-google',
  refresh: 'auth/refresh',
  register: 'auth/register',
  resend: 'auth/resend',
  user: 'auth/user',
  verify: 'auth/verify',
  users: 'users',
};
